In [1]:
import numpy as np

In [90]:
arreglo_numeros = np.array([1,2,3])
print(arreglo_numeros)

[1 2 3]


In [4]:
np.zeros([3,4])
np.zeros([3])
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
np.ones((5))
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
print(np.eye(4))
print(np.eye(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
print(np.arange(3,50))
print(np.arange(4,20,2))

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 4  6  8 10 12 14 16 18]


In [14]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [17]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
print(np.ones_like(np.arange(6).reshape(3,2)))
print(np.ones_like(np.arange(3)))

[[1 1]
 [1 1]
 [1 1]]
[1 1 1]


In [23]:
np.arange(24).reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [26]:
np.arange(10000).reshape(10,10,100)

array([[[   0,    1,    2, ...,   97,   98,   99],
        [ 100,  101,  102, ...,  197,  198,  199],
        [ 200,  201,  202, ...,  297,  298,  299],
        ...,
        [ 700,  701,  702, ...,  797,  798,  799],
        [ 800,  801,  802, ...,  897,  898,  899],
        [ 900,  901,  902, ...,  997,  998,  999]],

       [[1000, 1001, 1002, ..., 1097, 1098, 1099],
        [1100, 1101, 1102, ..., 1197, 1198, 1199],
        [1200, 1201, 1202, ..., 1297, 1298, 1299],
        ...,
        [1700, 1701, 1702, ..., 1797, 1798, 1799],
        [1800, 1801, 1802, ..., 1897, 1898, 1899],
        [1900, 1901, 1902, ..., 1997, 1998, 1999]],

       [[2000, 2001, 2002, ..., 2097, 2098, 2099],
        [2100, 2101, 2102, ..., 2197, 2198, 2199],
        [2200, 2201, 2202, ..., 2297, 2298, 2299],
        ...,
        [2700, 2701, 2702, ..., 2797, 2798, 2799],
        [2800, 2801, 2802, ..., 2897, 2898, 2899],
        [2900, 2901, 2902, ..., 2997, 2998, 2999]],

       ...,

       [[7000, 7001, 700

In [29]:
# Sumas
a = np.array([10,10,10])
b = np.array([5,5,5])
print(a + b)

[15 15 15]


In [30]:
# Resta
print(a-b)

[5 5 5]


In [31]:
# Multiplicacion
print(a*b)

[50 50 50]


In [32]:
# Division
print(a/b)

[2. 2. 2.]


In [35]:
# Operaciones
arreglo_dieciocho = np.arange(18)
print(arreglo_dieciocho/2)
print(arreglo_dieciocho%3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [36]:
# Expresiones
print(arreglo_dieciocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [42]:
# Multiplicación de varias dimensiones
A = np.arange(4).reshape(2,2)
print(A)
B = np.arange(4,8).reshape(2,2)
print(B)

A < B

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ True,  True],
       [ True,  True]])

In [44]:
# Multiplicacion dot
A.dot(B)
oli = np.arange(4).reshape(2,2)
np.dot(A,B,oli)
print(oli)
arreglo_tres = np.arange(3)
print(arreglo_tres)
arreglo_tres *= 3
print(arreglo_tres)

[[ 6  7]
 [26 31]]
[0 1 2]
[0 3 6]


In [46]:
# Operaciones conocidas en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())

45
0
9


In [51]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0)) # X
print(arreglo_tres_cuatro.sum(axis=1)) # Y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [54]:
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa *np.pi/180
print(angulos_cero_noventa_radianes)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [57]:
# Funciones trigonométricas
print(np.sin(angulos_cero_noventa_radianes))
print(np.cos(angulos_cero_noventa_radianes))
print(np.tan(angulos_cero_noventa_radianes))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [68]:
# Media
arreglo_diez = np.random.rand(10)*10
print(arreglo_diez)
print(np.mean(arreglo_diez))

[7.25041467 6.3046121  2.91473458 7.52985437 8.13705916 4.32554634
 4.41171225 2.49488946 8.31500647 9.07270887]
6.075653827576664


In [69]:
# Mediana
arreglo_diez = np.random.rand(10)*10
print(arreglo_diez)
print(np.median(arreglo_diez))

[6.79906776 0.77798312 9.84861923 3.61892148 8.64208207 5.81264867
 4.5256852  7.79442281 4.66802988 9.01869511]
6.305858215095967


In [70]:
# Desviacion estándar
print(arreglo_diez)
print (np.std(arreglo_diez))

[6.79906776 0.77798312 9.84861923 3.61892148 8.64208207 5.81264867
 4.5256852  7.79442281 4.66802988 9.01869511]
2.673171227924878


In [71]:
# Varianza
print(arreglo_diez)
print (np.var(arreglo_diez))

[6.79906776 0.77798312 9.84861923 3.61892148 8.64208207 5.81264867
 4.5256852  7.79442281 4.66802988 9.01869511]
7.145844413805399


In [75]:
# salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=',')
print(salarios.shape)

(11, 15)


In [92]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0])
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[2:8])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[:10:2])
print(arreglo_once_cuadrado[::-1])


[  0   1   4   9  16  25  36  49  64  81 100]
0
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 0  1  4  9 16]
[ 4  9 16 25 36 49]
[ 4 36]
[ 0  4 16 36 64]
[100  81  64  49  36  25  16   9   4   1   0]
