In [32]:
import numpy as np

In [33]:
arreglo_numeros = np.array([1,2,3])
print(arreglo_numeros)

[1 2 3]


In [34]:
np.zeros([3,4])
np.zeros([3])
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [35]:
np.ones((5))
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
print(np.eye(4))
print(np.eye(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
print(np.arange(3,50))
print(np.arange(4,20,2))

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 4  6  8 10 12 14 16 18]


In [38]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [39]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
print(np.ones_like(np.arange(6).reshape(3,2)))
print(np.ones_like(np.arange(3)))

[[1 1]
 [1 1]
 [1 1]]
[1 1 1]


In [41]:
np.arange(24).reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [42]:
np.arange(10000).reshape(10,10,100)

array([[[   0,    1,    2, ...,   97,   98,   99],
        [ 100,  101,  102, ...,  197,  198,  199],
        [ 200,  201,  202, ...,  297,  298,  299],
        ...,
        [ 700,  701,  702, ...,  797,  798,  799],
        [ 800,  801,  802, ...,  897,  898,  899],
        [ 900,  901,  902, ...,  997,  998,  999]],

       [[1000, 1001, 1002, ..., 1097, 1098, 1099],
        [1100, 1101, 1102, ..., 1197, 1198, 1199],
        [1200, 1201, 1202, ..., 1297, 1298, 1299],
        ...,
        [1700, 1701, 1702, ..., 1797, 1798, 1799],
        [1800, 1801, 1802, ..., 1897, 1898, 1899],
        [1900, 1901, 1902, ..., 1997, 1998, 1999]],

       [[2000, 2001, 2002, ..., 2097, 2098, 2099],
        [2100, 2101, 2102, ..., 2197, 2198, 2199],
        [2200, 2201, 2202, ..., 2297, 2298, 2299],
        ...,
        [2700, 2701, 2702, ..., 2797, 2798, 2799],
        [2800, 2801, 2802, ..., 2897, 2898, 2899],
        [2900, 2901, 2902, ..., 2997, 2998, 2999]],

       ...,

       [[7000, 7001, 700

In [43]:
# Sumas
a = np.array([10,10,10])
b = np.array([5,5,5])
print(a + b)

[15 15 15]

In [44]:
# Resta
print(a-b)

[5 5 5]


In [45]:
# Multiplicacion
print(a*b)

[50 50 50]


In [46]:
# Division
print(a/b)

[2. 2. 2.]


In [47]:
# Operaciones
arreglo_dieciocho = np.arange(18)
print(arreglo_dieciocho/2)
print(arreglo_dieciocho%3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [48]:
# Expresiones
print(arreglo_dieciocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [49]:
# Multiplicación de varias dimensiones
A = np.arange(4).reshape(2,2)
print(A)
B = np.arange(4,8).reshape(2,2)
print(B)

A < B

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


In [50]:
# Multiplicacion dot
A.dot(B)
oli = np.arange(4).reshape(2,2)
np.dot(A,B,oli)
print(oli)
arreglo_tres = np.arange(3)
print(arreglo_tres)
arreglo_tres *= 3
print(arreglo_tres)

[[ 6  7]
 [26 31]]
[0 1 2]
[0 3 6]


In [51]:
# Operaciones conocidas en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())

45
0
9


In [52]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0)) # X
print(arreglo_tres_cuatro.sum(axis=1)) # Y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [53]:
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa *np.pi/180
print(angulos_cero_noventa_radianes)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [54]:
# Funciones trigonométricas
print(np.sin(angulos_cero_noventa_radianes))
print(np.cos(angulos_cero_noventa_radianes))
print(np.tan(angulos_cero_noventa_radianes))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [55]:
# Media
arreglo_diez = np.random.rand(10)*10
print(arreglo_diez)
print(np.mean(arreglo_diez))

[5.73646622 8.01689179 3.22194834 5.94861917 0.23684417 5.88990093
 9.78137993 7.09791013 6.25143374 1.48377614]


5.36651705652725


In [56]:
# Mediana
arreglo_diez = np.random.rand(10)*10
print(arreglo_diez)
print(np.median(arreglo_diez))

[2.50069591 8.73821007 8.19445593 7.3070169  7.07347439 3.64016627
 1.4704331  3.7083528  6.21623404 7.01394278]
6.615088414549112


In [57]:
# Desviacion estándar
print(arreglo_diez)
print (np.std(arreglo_diez))

[2.50069591 8.73821007 8.19445593 7.3070169  7.07347439 3.64016627
 1.4704331  3.7083528  6.21623404 7.01394278]
2.4108086770596318


In [58]:
# Varianza
print(arreglo_diez)
print (np.var(arreglo_diez))

[2.50069591 8.73821007 8.19445593 7.3070169  7.07347439 3.64016627
 1.4704331  3.7083528  6.21623404 7.01394278]
5.8119984773860125


In [59]:
# salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=',')
print(salarios.shape)

OSError: data/salarios.csv not found.

In [60]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0])
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[2:-3])

[  0   1   4   9  16  25  36  49  64  81 100]
0
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[ 4  9 16 25 36 49]


# Arrange
Tenemos un arreglo de diez elementos y queremos hacer alguna cosa

In [62]:
estudiantes = np.array([['Array', 'Carlos', 'Vicente', 'Felipe'],
                       ['1','2','3','4'],
                       ['6.5','7.5','8','9']])

In [67]:
#Reshaping
paises_tuplas = np.array([('Ecuador', 'Colombia', 'Peru', 'Brazil'),
                          ('Mexico','Guatemala','Honduras','Venezuela')])

In [64]:
paises_tuplas 

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [65]:
paises_tuplas[0][0] = 'Estados Unidos'

In [68]:
paises_tuplas[0][0]

'Ecuador'

In [69]:
paises_tuplas.shape

(2, 4)

In [70]:
paises_tuplas.flatten().shape

(8,)

In [71]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [73]:
paises_tuplas.T

array([['Ecuador', 'Mexico'],
       ['Colombia', 'Guatemala'],
       ['Peru', 'Honduras'],
       ['Brazil', 'Venezuela']], dtype='<U9')

In [74]:
paises_tuplas.T.flatten()

array(['Ecuador', 'Mexico', 'Colombia', 'Guatemala', 'Peru', 'Honduras',
       'Brazil', 'Venezuela'], dtype='<U9')

In [76]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [77]:
paises_tuplas.reshape(4,2)

array([['Ecuador', 'Colombia'],
       ['Peru', 'Brazil'],
       ['Mexico', 'Guatemala'],
       ['Honduras', 'Venezuela']], dtype='<U9')

In [83]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala',
                   'Honduras',
                   'Venezuela',
                   'Argentina',
                   'Chile',
                   'Bolivia',
                   'Alemania'])

In [84]:
paises.reshape(3,-1,2) # 9 = X * 3    X=9/3   X=3

array([[['Ecuador', 'Colombia'],
        ['Peru', 'Brazil']],

       [['Mexico', 'Guatemala'],
        ['Honduras', 'Venezuela']],

       [['Argentina', 'Chile'],
        ['Bolivia', 'Alemania']]], dtype='<U9')

In [89]:
# Split
arreglo_split = np.arange(1,13)

In [93]:
np.split(arreglo_split,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [95]:
np.split(arreglo_split,[2,3,5,8])

[array([1, 2]),
 array([3]),
 array([4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12])]

In [97]:
#array_split_4_partes = np.array(array_split_4_partes)

In [98]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala'])

In [99]:
np.hsplit(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [100]:
np.split(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [102]:
paises_2d = np.array([['Ecuador',
                   'Colombia',
                   'Peru'],
                   ['Brazil',
                   'Mexico',
                   'Guatemala']])

In [104]:
np.vsplit(paises_2d,2)

[array([['Ecuador', 'Colombia', 'Peru']], dtype='<U9'),
 array([['Brazil', 'Mexico', 'Guatemala']], dtype='<U9')]

In [105]:
np.hsplit(paises_2d,3)

[array([['Ecuador'],
        ['Brazil']], dtype='<U9'), array([['Colombia'],
        ['Mexico']], dtype='<U9'), array([['Peru'],
        ['Guatemala']], dtype='<U9')]