In [3]:
import numpy as np

In [4]:
arreglo_numeros = np.array([1,2,3])
print(arreglo_numeros)

[1 2 3]


In [13]:
np.zeros((3,4))
np.zeros((3))
np.zeros((3,2,2,))
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones((5))
np.ones((5,3))
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
print(np.empty((3,2)))
print(np.zeros((3,4,2)))
print(np.empty((5)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[1. 1. 1. 1. 1.]


In [20]:
print(np.eye(4))
print(np.eye(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
print(np.arange(12))
print(np.arange(3,50))
print(np.arange(4,20,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 4  6  8 10 12 14 16 18]


In [28]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [32]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
print(np.ones_like(np.arange(6).reshape(3,2)))
print(np.ones_like(np.arange(3)))

[[1 1]
 [1 1]
 [1 1]]
[1 1 1]


In [38]:
np.arange(24).reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [45]:
np.arange(10000)
np.arange(10000).reshape(100,10,10)
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [46]:
# Sumas
a = np.array([10,10,10])
b = np.array([5,5,5])
print(a + b)

[15 15 15]


In [48]:
# Resta
print(a-b)

[5 5 5]


In [49]:
# Multiplicacion
print(a*b)

[50 50 50]


In [50]:
# Division
print(a/b)

[2. 2. 2.]


In [56]:
# Operaciones
arreglo_diez_ocho = np.arange(18)
print(arreglo_diez_ocho / 2 )
print(arreglo_diez_ocho % 3 )



[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [58]:
# Expresiones
print(arreglo_diez_ocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [72]:
# Multiplicacion de Varias dimensiones
A = np.arange(4).reshape(2,2)
print(A)
B = np.arange(4,8).reshape(2,2)
print(B)

A < B


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ True,  True],
       [ True,  True]])

In [94]:
# Multiplicacion dot
A.dot(B)
oli = np.arange(4).reshape(2,2)
np.dot(A,B,oli)
print(oli)


[[ 6  7]
 [26 31]]


In [93]:
arreglo_tres = np.arange(3)
print(arreglo_tres)
arreglo_tres += 3
print(arreglo_tres)

[0 1 2]
[3 4 5]


In [98]:
# Operaciones conocidas en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())


[0 1 2 3 4 5 6 7 8 9]
45
0
9


In [102]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0)) # X
print(arreglo_tres_cuatro.sum(axis=1)) # Y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


# Universal Functions
## Radianes


In [108]:
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa * np.pi/180
print(angulos_cero_noventa_radianes)
print(np.pi)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
3.141592653589793


In [109]:
# Funcion seno
print(np.sin(angulos_cero_noventa))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


In [110]:
# Funcion coseno
print(np.cos(angulos_cero_noventa))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [111]:
# Funcion tangente
print(np.tan(angulos_cero_noventa))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [124]:
# Media
arreglo_diez = np.random.rand(30)*10
print(arreglo_diez)
print(np.mean(arreglo_diez))

[8.83973736 6.75592639 1.15845086 1.10872111 3.22035357 9.11484448
 7.73072025 8.22809579 6.69768739 2.27460716 7.3470849  2.46058834
 8.12660114 7.74294219 1.61850203 5.21166999 5.16554842 4.6671159
 7.50734446 1.46568925 8.1426097  9.6938384  3.78701873 7.44791004
 4.60341812 4.84708205 8.44585179 0.68933551 8.68680561 6.44285149]
5.640965080588626


In [125]:
# Media
print(arreglo_diez)
print(np.median(arreglo_diez))

[8.83973736 6.75592639 1.15845086 1.10872111 3.22035357 9.11484448
 7.73072025 8.22809579 6.69768739 2.27460716 7.3470849  2.46058834
 8.12660114 7.74294219 1.61850203 5.21166999 5.16554842 4.6671159
 7.50734446 1.46568925 8.1426097  9.6938384  3.78701873 7.44791004
 4.60341812 4.84708205 8.44585179 0.68933551 8.68680561 6.44285149]
6.570269437885919


In [126]:
# Desviacion Estandar
print(arreglo_diez)
print(np.std(arreglo_diez))

[8.83973736 6.75592639 1.15845086 1.10872111 3.22035357 9.11484448
 7.73072025 8.22809579 6.69768739 2.27460716 7.3470849  2.46058834
 8.12660114 7.74294219 1.61850203 5.21166999 5.16554842 4.6671159
 7.50734446 1.46568925 8.1426097  9.6938384  3.78701873 7.44791004
 4.60341812 4.84708205 8.44585179 0.68933551 8.68680561 6.44285149]
2.762985476713553


In [127]:
# Varianza
print(arreglo_diez)
print(np.var(arreglo_diez))

[8.83973736 6.75592639 1.15845086 1.10872111 3.22035357 9.11484448
 7.73072025 8.22809579 6.69768739 2.27460716 7.3470849  2.46058834
 8.12660114 7.74294219 1.61850203 5.21166999 5.16554842 4.6671159
 7.50734446 1.46568925 8.1426097  9.6938384  3.78701873 7.44791004
 4.60341812 4.84708205 8.44585179 0.68933551 8.68680561 6.44285149]
7.634088744530019


In [132]:
# salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=',')
print(salarios)
print(salarios.shape)

[[ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]
 [ 1.  3.  4.  2.  5.  4.  3. 10. 20. 14. 12. 13. 15. 16. 14.]]
(11, 15)


In [148]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0])
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[2:8])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[:10:2])
print(arreglo_once_cuadrado[::-1])

[  0   1   4   9  16  25  36  49  64  81 100]
0
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 0  1  4  9 16]
[ 4  9 16 25 36 49]
[ 4 36]
[ 0  4 16 36 64]
[100  81  64  49  36  25  16   9   4   1   0]


# Arange
Tenemos un arreglo de 10 elementos y queremos ahcer alguna cosa

In [6]:


estudiantes = np.array([['Adrian','Carlos','Vicente','Felipe'],
                       [1,2,3,4],
                       [6.5,7.5,8,9]
                      ]
                      )

In [7]:
estudiantes

array([['Adrian', 'Carlos', 'Vicente', 'Felipe'],
       ['1', '2', '3', '4'],
       ['6.5', '7.5', '8', '9']], dtype='<U7')

In [8]:
estudiantes.shape

(3, 4)

In [9]:
for estudiante in estudiantes:
    print(estudiante)  # Dimensiones

['Adrian' 'Carlos' 'Vicente' 'Felipe']
['1' '2' '3' '4']
['6.5' '7.5' '8' '9']


In [10]:
for estudiante in estudiantes.flatten():
    print(estudiante)  # 1-D

Adrian
Carlos
Vicente
Felipe
1
2
3
4
6.5
7.5
8
9


In [11]:
for estudiante in estudiantes.flatten(order='F'):
    print(estudiante)  # 1-D

Adrian
1
6.5
Carlos
2
7.5
Vicente
3
8
Felipe
4
9


In [12]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# nditer
for i in np.nditer(arreglo_tres_cuatro):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [17]:
# nditer
for i in np.nditer(arreglo_tres_cuatro, order="F", op_flags=['readwrite']):
    print(i)
    i[...] = i*i
    print(i)

0
0
4
16
8
64
1
1
5
25
9
81
2
4
6
36
10
100
3
9
7
49
11
121


In [23]:
# Reshaping
paises_tuplas = np.array([('Ecuador','Colombia','Peru','Brazil'),
                          ('Mexico','Guatemala','Honduras','Venezuela')])

In [19]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [21]:
paises_tuplas[0][0] = 'Estados Unidos'

In [24]:
paises_tuplas[0][0]

'Ecuador'

In [25]:
paises_tuplas.shape

(2, 4)

In [26]:
paises_tuplas.flatten()

array(['Ecuador', 'Colombia', 'Peru', 'Brazil', 'Mexico', 'Guatemala',
       'Honduras', 'Venezuela'], dtype='<U9')

In [27]:
paises_tuplas.flatten().shape

(8,)

In [28]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [29]:
paises_tuplas.T

array([['Ecuador', 'Mexico'],
       ['Colombia', 'Guatemala'],
       ['Peru', 'Honduras'],
       ['Brazil', 'Venezuela']], dtype='<U9')

In [30]:
paises_tuplas.T.flatten()

array(['Ecuador', 'Mexico', 'Colombia', 'Guatemala', 'Peru', 'Honduras',
       'Brazil', 'Venezuela'], dtype='<U9')

In [36]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brazil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [37]:
paises_tuplas.reshape(4,2)

array([['Ecuador', 'Colombia'],
       ['Peru', 'Brazil'],
       ['Mexico', 'Guatemala'],
       ['Honduras', 'Venezuela']], dtype='<U9')

In [42]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala',
                   'Honduras',
                   'Venezuela',
                   'Argentina',
                   'Chile',
                   'Bolivia',
                   'Alemania'])

In [44]:
paises.reshape(3,-1,2)  #  9    9 = X * 3    X = 9/3 = 3

array([[['Ecuador', 'Colombia'],
        ['Peru', 'Brazil']],

       [['Mexico', 'Guatemala'],
        ['Honduras', 'Venezuela']],

       [['Argentina', 'Chile'],
        ['Bolivia', 'Alemania']]], dtype='<U9')

In [ ]:
# Split

In [51]:
arreglo_split = np.arange(1,13)

In [54]:
arreglo_split.shape

(12,)

In [52]:
np.split(arreglo_split,[2,3,5,7,8])

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [63]:
array_split_4_partes = np.array(array_split_4_partes)

In [66]:
array_split_4_partes.shape

(5,)

In [67]:
paises = np.array(['Ecuador',
                   'Colombia',
                   'Peru',
                   'Brazil',
                   'Mexico',
                   'Guatemala'])

In [69]:
np.hsplit(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [70]:
np.split(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brazil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [74]:
paises_2d = np.array([['Ecuador',
                   'Colombia',
                   'Peru'], 
                   ['Brazil',
                   'Mexico',
                   'Guatemala']])

In [76]:
print(paises_2d.shape)
np.vsplit(paises_2d,2)

(2, 3)


[array([['Ecuador', 'Colombia', 'Peru']], dtype='<U9'),
 array([['Brazil', 'Mexico', 'Guatemala']], dtype='<U9')]

In [78]:
np.hsplit(paises_2d,3)

[array([['Ecuador'],
        ['Brazil']], dtype='<U9'), array([['Colombia'],
        ['Mexico']], dtype='<U9'), array([['Peru'],
        ['Guatemala']], dtype='<U9')]