In [1]:
import numpy as np

In [2]:
arreglo_diez_seis = np.arange(16).reshape(4,4)
arreglo_diez_seis

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
indice_booleano_mayores_a_ocho = arreglo_diez_seis > 8
indice_booleano_mayores_a_ocho

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
print(arreglo_diez_seis[indice_booleano_mayores_a_ocho])

[ 9 10 11 12 13 14 15]


In [6]:
print(np.count_nonzero(indice_booleano_mayores_a_ocho))

7


In [7]:
print(np.sum(indice_booleano_mayores_a_ocho))

7


In [8]:
print(np.sum(indice_booleano_mayores_a_ocho,axis=1))

[0 0 3 4]


In [9]:
indice_booleano_mayor_a_veinte = arreglo_diez_seis > 20
print(np.any(indice_booleano_mayor_a_veinte))

False


In [13]:
indice_booleano_menor_a_veinte = arreglo_diez_seis < 20
print(np.all(indice_booleano_menor_a_veinte))
print(np.all(indice_booleano_menor_a_veinte,axis=1))

True
[ True  True  True  True]
