In [0]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 10, 10, 10, 10])
print(a*b)


[10 20 30 40 50]


In [6]:
d = np.ones((4,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
alturas = [1.6,1.65,1.8] # Metros

In [9]:
pesos = [165,170,185] # Libras

In [10]:
datos_estudiantes = np.array([alturas,pesos])
print(datos_estudiantes)

[[  1.6    1.65   1.8 ]
 [165.   170.   185.  ]]


In [19]:
transformacion = np.array([100, 2.2])
transformacionuno = np.array([[100], [2.2]])


In [21]:
transformacionuno.shape

(2, 1)

In [13]:
datos_estudiantes.shape

(2, 3)

In [20]:
datos_estudiantes * transformacionuno

array([[160., 165., 180.],
       [363., 374., 407.]])