In [1]:
import numpy as np

## 2) Crear un vector de ceros de tamaño 10

In [3]:
vector_ceros_diez = np.zeros(10)
print(vector_ceros_diez)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
vector_ceros_diez_cinco = vector_ceros_diez
vector_ceros_diez_cinco[5] = 1
print(vector_ceros_diez_cinco)


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [7]:
vector_cincuenta = np.arange(50)
vector_cincuenta_reverso = vector_cincuenta[::-1]
print(vector_cincuenta_reverso)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [9]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6) Encontrar los indices que no sean cero en un arreglo

In [20]:
arreglo = np.asarray([1,2,0,0,4,0])
indice_no_cero = arreglo != 0
print(indice_no_cero)

[ True  True False False  True False]
