In [1]:
import numpy as np

## 2) Crear un vector de ceros de tamaño 10

In [3]:
vector_ceros_diez = np.zeros(10)
print(vector_ceros_diez)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
vector_ceros_diez_cinco = vector_ceros_diez
vector_ceros_diez_cinco[5] = 1
print(vector_ceros_diez_cinco)


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [7]:
vector_cincuenta = np.arange(50)
vector_cincuenta_reverso = vector_cincuenta[::-1]
print(vector_cincuenta_reverso)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [9]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6) Encontrar los indices que no sean cero en un arreglo

In [20]:
arreglo = np.asarray([1,2,0,0,4,0])
indice_no_cero = arreglo != 0
print(indice_no_cero)

[ True  True False False  True False]


## 7) Crear una matriz de identidad 3 x 3

In [24]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [43]:
matriz_tres_tres_tres = np.random.randint(100, size=27).reshape(3,3,3)
print(matriz_tres_tres_tres)

[[[46 62 56]
  [41 71 48]
  [36 67 38]]

 [[45 96  5]
  [68 89 48]
  [97 77 22]]

 [[77 59 62]
  [ 0 26 84]
  [37 33 65]]]


## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [49]:
matriz_diez_diez = np.random.randint(1000, size=100).reshape(10,10)
print(matriz_diez_diez)
print("Mayor: %d" % (matriz_diez_diez.max()))
print("Menor: %d" % (matriz_diez_diez.min()))

[[ 71  17  96  23 426 199 346 227 327 870]
 [982 391 247  56 112  47 943 234  70 575]
 [116 464 774 578 911 895  94 388 100  45]
 [793 577 173  68 646 764 656 298 552 974]
 [101 427 794 798 681 648 233 911 444 589]
 [200 310 513 116  60 865 522 546 462 460]
 [696 979 627 735 679 308 819 500 975 619]
 [708 322 329 457 317 420  42 179 825 635]
 [355 669 703 832 826 691 551 238 338 351]
 [196 332 684 718 646 509 262 315 582 649]]
Mayor: 982
Menor: 17
